import React from 'react';

const howItWorksData = [
  {
    id: 1,
    icon: './images/icons/energy.svg',
    title: 'Renewable Energy Projects',
    description:
      'Solar farms, wind turbines, and hydroelectric plants generate clean energy. The revenue generated from these sources forms the basis of Renewtrade\'s income-sharing model.',
  },
  {
    id: 2,
    icon: './images/icons/token.svg',
    title: 'The Renewtrade Token',
    description:
      'Tokenholders receive a share of the profits generated by these energy projects. Up to 50% of the net profits are distributed based on the tiered structure of investments.',
  },
  {
    id: 3,
    icon: './images/icons/trust.svg',
    title: 'Transparency & Trust',
    description:
      'Built on blockchain, all transactions are publicly recorded and verified. Independent audits are conducted to ensure accurate revenue distributions.',
  },
];

const HowItWorks = () => {
  return (
    <div className="how-it-section">
      <div className="container">
        <div className="row">
          <div className="col-md-7">
            <div className="how-it-left">
              <div className="how-it-img">
                <img src="./images/img/how-work-img.png" alt="How it works" />
              </div>
            </div>
          </div>
          <div className="col-md-5">
            <div className="how-it-right">
              <div className="how-it-text">
                <div className="section-title">
                    <h2>How It Works</h2>
                </div>
                <div className="how-it-content">
                  <ul>
                    {howItWorksData.map((item) => (
                      <li key={item.id}>
                        <div className="icon">
                          <img src={item.icon} alt="icon" />
                        </div>
                        <div className="detail">
                          <h3>{item.title}</h3>
                          <p>{item.description}</p>
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HowItWorks;
